@startuml

class BovedaTransformers {}

class ExcepcionBovedaTransformers {}

class Transformer {}

class Vector<Transformer>{}

BovedaTransformers ..> ExcepcionBovedaTransformers
BovedaTransformers ..> Transformer
BovedaTransformers ..> Vector
Transformer ..> Vector

@enduml
