@startuml
class BovedaCristales {
}

class ExceptionBovedaCristales{
}

class Cristal {
}

class Vector<T>{
}

BovedaCristales ..>ExceptionBovedaCristales
BovedaCristales ..> Cristal
BovedaCristales ..> Vector

@enduml